### ISSUE TITLE
Drag-and-drop from antiX 19.2's default file manager to SpaceFM halts GUI

### ISSUE THREAD

**Issue by rayluo** [PPC-scripts/android-device-USB-connect#1]
First of all, thanks (again) PPC for providing such a useful script! The following issue might not be "fault" of this script, I'm just documenting it here for future reference.

This script can successfully mount my Android device and automatically starts a SpaceFM. Copy-and-paste within such SpaceFM window seems to work just fine. However, if I happen to do drag-and-drop from antiX 19.2's default file manager (I don't know its name) to SpaceFM, it almost halts my desktop GUI:

* my mouse cursor becomes an add-file icon (a file, a hand, and a plus sign), the cursor itself can still be moved around, but any mouse click would do nothing.
* At this point, attempting ALT+TAB to switch to different app, simply won't work either, because somehow the Desktop automatically brings me back to the current front-ground app, usually the SpaceFM.
* However, it happens that I can use ALT+F3 to switch to different apps, and then use keyboard-only to interact with them. For example, I can switch back to the terminal, to CTRL+C and stop such android-mount script, and gracefully close other opened apps.
* Eventually, this situation can only be recovered by a reboot.

**Comment by PPC-scripts** [comment]
Hi, Ray!
 Thanks for your your thanks ( :-) ) and also for your input.
 I believe that this "spacefm" freeze is not due to the script, but it's a SpaceFm / antiX / hardware issue. My reasons for thinking that are the following:
 - The script basically creates a folder in the user's home folder, that will be used as a mount point, and then simply runs 'jmtsfs [mountpoint]' (the command line program that mounts android devices), and runs the default file manager (my case it happens to be spacefm) , displaying the folder's contents and then exits (ok, there can be some more extra steps, but that's not relevant to this point).
 - This means that, when spacefm freezes, the script is no longer running (it does not keep running on the background- it's the reason why, if you want to unmount the android device using the script, you have to run it again)
 - I think that probably that spacefm freeze is due to lack of computer resources because I run antix 19 on my desktops both at home and at my office and I noticed this:
 My home computer if multicore and my office's one is single core. I copied, from my home's pc to my phone several files without any problems, but, when I copied those same files from  my phone to my more modest office computer, spacefm froze for about 20-30 seconds, and then I was able to copy the files...
 - The mouse cursor situation you mentioned happens to me, every now and then, on spacefm, when not using any android device, but copying file to/from usb pendrives... 

 You can test if this is a spacefm or antiX related problem by doing the following experiment:
 run  the new "antiX only" script.

 Your device's contents should be displayed using rox... See if there's a freeze, using only that particular file manager...

 Sorry for the long response, and please, do share your findings with me 

EDIT: I tweaked the script a bit and made a "antiX only" version, that uses the default file manager as set via Control Centre- Default applications...
 If there are any updates to the script, I'll probably do them to this version only...

P.

**Comment by rayluo** [comment]
Thanks for the response, @PPC-scripts !

> I believe that this "spacefm" freeze is not due to the script, but it's a SpaceFm / antiX / hardware issue. My reasons for thinking that are the following: The script basically creates ... and then exits.
This means that, when spacefm freezes, the script is no longer running (it does not keep running on the background

That is probably how the script is supposed to work. But, if my memory serves me right, both times I observed the aforementioned symptom, the script was somehow still running on front-ground, thus I were doing "switch back to the terminal, to CTRL+C and stop such android-mount script", as mentioned in this issue's description. So, this discrepancy might be a hint to what went wrong. 

> please, do share your findings with me

Sure.

I tested the new "antiX only" version. The first attempt did not connect, but I guess that was the typical hiccup on connecting with USB devices. Following the instruction from a pop-up window, I unplug and re-plug my Android tablet, and it worked this time.

And yes, this time, the default file explorer in antiX was automatically launched (rather than SpaceFM), so that the drag-and-drop between it and another "antiX default file explorer" works smoothly, as they should be.

One thing though. After I finish my copy-and-paste, I find my android device is NOT shown up in the "Unplug Removable Device" tool's device list. Right-clicking the mounted folder icon and choose "Eject" or "Unmount", I get this error:

```
Eject '/home/demo/android_device'
eject: tried to use `jmtpfs' as device name but it is no block device
eject: unable to find or open device for: `/home/demo/android_device'
eject failed
```

**Comment by PPC-scripts** [comment]
Sorry, Ray, but I don't use Rox file manager, so I have no idea how to unmount android devices using it,.. Devices mounted using the MTP protocol (like current android devices) are not "normal" removable devices, they need to be unmounted using a special command... Spacefm allows to simply click the device name and unmount it, but it's a more advanced file manager than Rox...

**Solution** Try re-running the script - it was made so, when starting, first check if the android device is already mounted. If so, it offers to access the device OR to unmount it. If you select umount, it tries to do so  and, if successful, displays a warning, telling the user that it's safe to remove the device.
 Note: I tested the script with Rox, and, if you unmount the device with it's contents still being displayed in the file manager's window, it's to be expected that, when the device is unmounted, Rox displays a warning that the folder does not exist any more (after all it's removed after unmounting...)

 **Question;** I don't usually like programs or scripts that keep running in the background, but do you think it would be useful if the script created a icon on the tray, that users could click to access or unmount the device? I could, if I have time, try to implement that. I haven't done so because I deslike having my RAM occupied by unwanted programs. 

 **Suggestion:** if you use this script a lot, you can do like me, if you use the default icewm desktop:
I have the script's icon on the toolbar,so I can mount / unmount my devices with a single click. I do that using the .desktop file that I made available in antix's thread, and putting it in the toolbar using "icewm's toolbar icon manager".
 You can put the script's icon directly on the toolbar by usinf a simpler process:
1- antiX's menu - Control Centre -  Edit Icewm... - Toolbar tab and add a line similar to this:
` prog "Android Device Mounter/Unmounter" /usr/share/icons/papirus-antix/24x24/devices/phone.png [fullpath_to_the_script]`
 2- Save the changes and Menu - arrow next to Logout button - Restart Icewm
 3- The "smartphone" icon should appear on your toolbar. Click it to mount or unmount android devices...

 **The good news** is that Anticapitalista is going to make the script, and it's desktop file available out of the box in antiX, as soon as it's translations are finished, so, this entire process will be a lot easier on the future... Probably just Menu- antiX - Android Device USB Connect...)

P.

**Comment by rayluo** [comment]
> Devices mounted using the MTP protocol (like current android devices) are not "normal" removable devices, they need to be unmounted using a special command... Spacefm allows to simply click the device name and unmount it, but it's a more advanced file manager than Rox...

Good to know! Thanks for the info. If this repo will be a stand-alone project, this info should go into a README.md file.

> 
> **Solution** Try re-running the script - it was made so, when starting, first check if the android device is already mounted. If so, it offers to access the device OR to unmount it. If you select umount, it tries to do so and, if successful, displays a warning, telling the user that it's safe to remove the device.

Good to know! I did not know that. And this info should be displayed at the very last line - ideally with one blank line to separate/highlight it from the one dozen lines before it.

> Note: I tested the script with Rox, and, if you unmount the device with it's contents still being displayed in the file manager's window, it's to be expected that, when the device is unmounted, Rox displays a warning that the folder does not exist any more (after all it's removed after unmounting...)

Yes that is the Rox file manager's behavior.


> **Question;** I don't usually like programs or scripts that keep running in the background, but do you think it would be useful if the script created a icon on the tray, that users could click to access or unmount the device? I could, if I have time, try to implement that. I haven't done so because I deslike having my RAM occupied by unwanted programs.

From a (average Joe's) user experience standpoint, presumably, yes. Because that was also how a normal USB drive's behavior in some mainstream OSes.

From RAM consumption standpoint, personally I don't think that is a decision factor. Because I assume its memory footprint is as small as one more bash process. Also because, due to the perceived unreliable nature of a usb connection, I would tend to finish my file transferring asap and then disconnect it, i.e. I won't really do heavy and prolonged multi-tasking during the transferring.

From a Return-on-Investment (RoI) standpoint, you need to balance your effort and the quality of the outcome. If extra function hints potentially less reliable script implementation, I would rather use it as-is. :-)

> 
> **Suggestion:** if you use this script a lot, you can do like me, if you use the default icewm desktop:
> I have the script's icon on the toolbar,so I can mount / unmount my devices with a single click. I do that using the .desktop file that I made available in antix's thread, and putting it in the toolbar using "icewm's toolbar icon manager".
> You can put the script's icon directly on the toolbar by usinf a simpler process:
> 1- antiX's menu - Control Centre - Edit Icewm... - Toolbar tab and add a line similar to this:
> ` prog "Android Device Mounter/Unmounter" /usr/share/icons/papirus-antix/24x24/devices/phone.png [fullpath_to_the_script]`
> 2- Save the changes and Menu - arrow next to Logout button - Restart Icewm
> 3- The "smartphone" icon should appear on your toolbar. Click it to mount or unmount android devices...

Good to know! Another topic belongs to the README.

> **The good news** is that Anticapitalista is going to make the script, and it's desktop file available out of the box in antiX, as soon as it's translations are finished, so, this entire process will be a lot easier on the future... Probably just Menu- antiX - Android Device USB Connect...)
> 
> P.

Yeah I noticed that too, however, translation alone won't make "this entire process a lot easier". You would need to clarify with him on:

* Which repo will become the main repo of this script project. We could use either this repo here, or the one he cloned at GitLab, but NOT BOTH. This kind of bug report, feature suggestion, relevant discussion, ..., should really go into one central place.
* Perhaps Anti would prefer his GitLab repo, and if you would also agree, then you can ask him to make you a contributor with write permission on that repo. And then optionally close this one.

**Comment by PPC-scripts** [comment]
Ray:

 I hope that now you can mount your devices, copy/paste your files and then unmount them properly.
 If there are more problems mounting the devices I can re-add a "sleep one second" before the process, so even older devices have time to properly enable the mount process.
 
I updated the "read me" file, using bold letters in the more important info about Mounting and Unmounting android devices. I also added a small how-to add the script's icon to Icewm's toolbar, on the bottom.

 For now, i don't, in fact, have the time to add the tray icon to mount/unmount devices, as far as I can tell, it's the only possible "feature" still lacking (if one thinks it should exist).

 All bug reports/suggestions should be directed at me, at this (original) github page, that I'll check now and then. I'll try to solve what I can and then warn anticapitalista to update his fork.

P.
